# Generated by Django 4.1.7 on 2023-05-12 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                ("uid", models.AutoField(primary_key=True, serialize=False)),
                (
                    "idnum",
                    models.CharField(max_length=18, unique=True, verbose_name="身份证号"),
                ),
                ("pwd", models.CharField(max_length=63, verbose_name="密码")),
                (
                    "atype",
                    models.SmallIntegerField(
                        choices=[(0, "管理员"), (1, "体检用户"), (2, "医务人员")],
                        verbose_name="账户类型",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Diagnose",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "value",
                    models.CharField(max_length=64, unique=True, verbose_name="诊断结果"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                ("eid", models.AutoField(primary_key=True, serialize=False)),
                ("time", models.DateTimeField(verbose_name="安排时间")),
                ("desc", models.TextField(max_length=300, verbose_name="备注")),
                (
                    "status",
                    models.SmallIntegerField(
                        choices=[(0, "可编辑"), (1, "已锁定"), (2, "已存档")],
                        default=0,
                        verbose_name="状态",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Item",
            fields=[
                ("item_id", models.AutoField(primary_key=True, serialize=False)),
                ("item", models.CharField(max_length=80, verbose_name="项目名称")),
                (
                    "cate",
                    models.IntegerField(
                        choices=[(0, "数值型"), (1, "非数值型")],
                        default=0,
                        verbose_name="结果类型",
                    ),
                ),
                (
                    "low_lmt",
                    models.DecimalField(
                        decimal_places=1, max_digits=5, null=True, verbose_name="参考值下限"
                    ),
                ),
                (
                    "high_lmt",
                    models.DecimalField(
                        decimal_places=1, max_digits=5, null=True, verbose_name="参考值上限"
                    ),
                ),
                ("unit", models.CharField(max_length=10, verbose_name="单位")),
            ],
        ),
        migrations.CreateModel(
            name="ItemType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("index", models.PositiveIntegerField(unique=True, verbose_name="序号")),
                (
                    "name",
                    models.CharField(max_length=64, unique=True, verbose_name="类别名称"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Staff",
            fields=[
                (
                    "account",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="pe_sys_demo.account",
                    ),
                ),
                ("name", models.CharField(max_length=80, verbose_name="姓名")),
                (
                    "gender",
                    models.SmallIntegerField(
                        choices=[(0, "男"), (1, "女")], default=0, verbose_name="性别"
                    ),
                ),
                ("phone", models.CharField(max_length=15, verbose_name="手机号")),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "account",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="pe_sys_demo.account",
                    ),
                ),
                ("name", models.CharField(max_length=80, verbose_name="姓名")),
                ("phone", models.CharField(max_length=15, verbose_name="手机号")),
                (
                    "gender",
                    models.SmallIntegerField(
                        choices=[(0, "男"), (1, "女")], default=0, verbose_name="性别"
                    ),
                ),
                (
                    "marriage",
                    models.SmallIntegerField(
                        choices=[(0, "未婚"), (1, "已婚")], default=0, verbose_name="婚姻状况"
                    ),
                ),
                ("dep", models.CharField(max_length=50, verbose_name="所属科室")),
                ("career", models.CharField(max_length=80, verbose_name="工作岗位")),
                ("factor", models.CharField(max_length=128, verbose_name="有害因素")),
            ],
        ),
        migrations.CreateModel(
            name="UserEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.SmallIntegerField(
                        choices=[(0, "未完成"), (1, "已完成")], default=0, verbose_name="状态"
                    ),
                ),
                ("review", models.TextField(verbose_name="处置意见")),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pe_sys_demo.event",
                        verbose_name="体检事件",
                    ),
                ),
                (
                    "staff",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="pe_sys_demo.staff",
                        verbose_name="主检医师",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pe_sys_demo.user",
                        verbose_name="用户",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Record",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rec", models.CharField(max_length=64, verbose_name="体检结果")),
                (
                    "sign",
                    models.SmallIntegerField(
                        choices=[(0, "低"), (1, ""), (2, "高")],
                        default=1,
                        verbose_name="异常情况",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pe_sys_demo.item",
                        verbose_name="体检项目",
                    ),
                ),
                (
                    "userevent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pe_sys_demo.userevent",
                        verbose_name="体检事件",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="item",
            name="itype",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="pe_sys_demo.itemtype",
                verbose_name="所属类别",
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="ref",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="pe_sys_demo.diagnose",
                verbose_name="正常值",
            ),
        ),
    ]
